"""add full_name and poste to users

Revision ID: 5ffe438fc09d
Revises: c1b6ccaddb19
Create Date: 2026-05-25 02:57:32.467793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ffe438fc09d'
down_revision: Union[str, Sequence[str], None] = 'c1b6ccaddb19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_cv_cache_expires'), table_name='cv_parse_cache')
    op.drop_index(op.f('idx_cv_cache_md5'), table_name='cv_parse_cache')
    op.drop_table('cv_parse_cache')
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('poste', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'poste')
    op.drop_column('users', 'full_name')
    op.create_table('cv_parse_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('md5_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('parsed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cv_parse_cache_pkey')),
    sa.UniqueConstraint('md5_hash', name=op.f('cv_parse_cache_md5_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_cv_cache_md5'), 'cv_parse_cache', ['md5_hash'], unique=False)
    op.create_index(op.f('idx_cv_cache_expires'), 'cv_parse_cache', ['expires_at'], unique=False)
    # ### end Alembic commands ###
