"""add_interviews_table

Revision ID: 72ceb9b1845a
Revises: f1a7a96be983
Create Date: 2026-05-09 22:02:59.795221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72ceb9b1845a'
down_revision: Union[str, Sequence[str], None] = 'f1a7a96be983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=False),
    sa.Column('candidate_email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('round', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_id'), 'interviews', ['id'], unique=False)
    op.drop_index(op.f('idx_cv_cache_expires'), table_name='cv_parse_cache')
    op.drop_index(op.f('idx_cv_cache_md5'), table_name='cv_parse_cache')
    op.drop_table('cv_parse_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_parse_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('md5_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('parsed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cv_parse_cache_pkey')),
    sa.UniqueConstraint('md5_hash', name=op.f('cv_parse_cache_md5_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_cv_cache_md5'), 'cv_parse_cache', ['md5_hash'], unique=False)
    op.create_index(op.f('idx_cv_cache_expires'), 'cv_parse_cache', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_interviews_id'), table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###
