"""add_new_statuses_and_events

Revision ID: f1a7a96be983
Revises: 4ac650300dae
Create Date: 2026-05-02 15:01:46.676405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1a7a96be983'
down_revision: Union[str, Sequence[str], None] = '4ac650300dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_events_id'), 'application_events', ['id'], unique=False)
    op.drop_index(op.f('idx_cv_cache_expires'), table_name='cv_parse_cache')
    op.drop_index(op.f('idx_cv_cache_md5'), table_name='cv_parse_cache')
    op.drop_table('cv_parse_cache')
    op.add_column('applications', sa.Column('signal_final', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('test_opened_at', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('test_available_from', sa.DateTime(), nullable=True))
    op.add_column('applications', sa.Column('gdpr_consent', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('gdpr_consent_at', sa.DateTime(), nullable=True))
    # ── Créer type Enum application_status_v2 ───────────────
    op.execute("""
        CREATE TYPE application_status_v2 AS ENUM (
            'APPLIED', 'ANALYZED', 'MATCHED', 'PENDING', 'PRESELECTED',
            'TEST_READY', 'TEST_SENT', 'TEST_IN_PROGRESS', 'TEST_COMPLETED',
            'TECHNICAL_REVIEW_PENDING', 'INTERVIEW_ELIGIBLE',
            'INTERVIEW_SCHEDULED', 'INTERVIEW_DONE', 'TECH_EVALUATED',
            'ACCEPTED', 'REJECTED_AUTO', 'REJECTED_FINAL',
            'ERROR', 'ERROR_RETRY'
        )
    """)
    # ── Supprimer default → changer type → remettre default ─
    op.execute("ALTER TABLE applications ALTER COLUMN status_v2 DROP DEFAULT")
    op.execute("""
        ALTER TABLE applications
        ALTER COLUMN status_v2
        TYPE application_status_v2
        USING status_v2::text::application_status_v2
    """)
    op.execute("ALTER TABLE applications ALTER COLUMN status_v2 SET DEFAULT 'APPLIED'::application_status_v2")
    op.create_index(op.f('ix_applications_status_v2'), 'applications', ['status_v2'], unique=False)
    op.drop_constraint(op.f('booking_tokens_token_key'), 'booking_tokens', type_='unique')
    op.create_index(op.f('ix_booking_tokens_id'), 'booking_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_booking_tokens_token'), 'booking_tokens', ['token'], unique=True)
    op.drop_column('cv_profiles', 'experience')
    op.create_index(op.f('ix_interview_slots_id'), 'interview_slots', ['id'], unique=False)
    op.create_index(op.f('ix_interview_slots_job_id'), 'interview_slots', ['job_id'], unique=False)
    op.alter_column('invitation_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('invitation_tokens_token_key'), 'invitation_tokens', type_='unique')
    op.create_index(op.f('ix_invitation_tokens_id'), 'invitation_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_invitation_tokens_token'), 'invitation_tokens', ['token'], unique=True)
    op.add_column('jobs', sa.Column('test_available_from', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('test_duration', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('test_validated', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('test_id_validated', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('pipeline_mode', sa.String(), nullable=True))
    op.alter_column('manager_jobs', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('manager_jobs', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_manager_jobs_id'), 'manager_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_manager_jobs_job_id'), 'manager_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_manager_jobs_manager_id'), 'manager_jobs', ['manager_id'], unique=False)
    # ── Convertir données FR → EN avant de changer le type ──
    op.execute("UPDATE manager_reviews SET decision = 'RECOMMENDED' WHERE decision = 'RECOMMANDÉ'")
    op.execute("UPDATE manager_reviews SET decision = 'TO_REVIEW'   WHERE decision = 'À_REVOIR'")
    op.execute("UPDATE manager_reviews SET decision = 'REFUSED'      WHERE decision = 'REFUSÉ'")

    # ── Créer type Enum manager_decision_v2 ─────────────────
    op.execute("""
        CREATE TYPE manager_decision_v2 AS ENUM (
            'RECOMMENDED', 'TO_REVIEW', 'REFUSED'
        )
    """)
    op.execute("""
        ALTER TABLE manager_reviews
        ALTER COLUMN decision
        TYPE manager_decision_v2
        USING decision::text::manager_decision_v2
    """)
    op.create_index(op.f('ix_manager_reviews_application_id'), 'manager_reviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_manager_reviews_id'), 'manager_reviews', ['id'], unique=False)
    op.alter_column('tests', 'test_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('idx_tests_job_id'), table_name='tests')
    op.drop_index(op.f('idx_tests_job_key'), table_name='tests')
    op.create_index(op.f('ix_tests_job_id'), 'tests', ['job_id'], unique=False)
    op.create_index(op.f('ix_tests_job_key'), 'tests', ['job_key'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'RH'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'RH'::character varying"))
    op.drop_index(op.f('ix_tests_job_key'), table_name='tests')
    op.drop_index(op.f('ix_tests_job_id'), table_name='tests')
    op.create_index(op.f('idx_tests_job_key'), 'tests', ['job_key'], unique=False)
    op.create_index(op.f('idx_tests_job_id'), 'tests', ['job_id'], unique=False)
    op.alter_column('tests', 'test_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_manager_reviews_id'), table_name='manager_reviews')
    op.drop_index(op.f('ix_manager_reviews_application_id'), table_name='manager_reviews')
    op.alter_column('manager_reviews', 'decision',
               existing_type=sa.Enum('RECOMMENDED', 'TO_REVIEW', 'REFUSED', name='manager_decision_v2'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_manager_jobs_manager_id'), table_name='manager_jobs')
    op.drop_index(op.f('ix_manager_jobs_job_id'), table_name='manager_jobs')
    op.drop_index(op.f('ix_manager_jobs_id'), table_name='manager_jobs')
    op.alter_column('manager_jobs', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('manager_jobs', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('jobs', 'pipeline_mode')
    op.drop_column('jobs', 'test_id_validated')
    op.drop_column('jobs', 'test_validated')
    op.drop_column('jobs', 'test_duration')
    op.drop_column('jobs', 'test_available_from')
    op.drop_index(op.f('ix_invitation_tokens_token'), table_name='invitation_tokens')
    op.drop_index(op.f('ix_invitation_tokens_id'), table_name='invitation_tokens')
    op.create_unique_constraint(op.f('invitation_tokens_token_key'), 'invitation_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.alter_column('invitation_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_interview_slots_job_id'), table_name='interview_slots')
    op.drop_index(op.f('ix_interview_slots_id'), table_name='interview_slots')
    op.add_column('cv_profiles', sa.Column('experience', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_booking_tokens_token'), table_name='booking_tokens')
    op.drop_index(op.f('ix_booking_tokens_id'), table_name='booking_tokens')
    op.create_unique_constraint(op.f('booking_tokens_token_key'), 'booking_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_applications_status_v2'), table_name='applications')
    op.alter_column('applications', 'status_v2',
               existing_type=sa.Enum('APPLIED', 'ANALYZED', 'MATCHED', 'PENDING', 'PRESELECTED', 'TEST_READY', 'TEST_SENT', 'TEST_IN_PROGRESS', 'TEST_COMPLETED', 'TECHNICAL_REVIEW_PENDING', 'INTERVIEW_ELIGIBLE', 'INTERVIEW_SCHEDULED', 'INTERVIEW_DONE', 'TECH_EVALUATED', 'ACCEPTED', 'REJECTED_AUTO', 'REJECTED_FINAL', 'ERROR', 'ERROR_RETRY', name='application_status_v2'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text("'APPLIED'::character varying"))
    op.drop_column('applications', 'gdpr_consent_at')
    op.drop_column('applications', 'gdpr_consent')
    op.drop_column('applications', 'test_available_from')
    op.drop_column('applications', 'test_opened_at')
    op.drop_column('applications', 'signal_final')
    op.create_table('cv_parse_cache',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('md5_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('parsed_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cv_parse_cache_pkey')),
    sa.UniqueConstraint('md5_hash', name=op.f('cv_parse_cache_md5_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_cv_cache_md5'), 'cv_parse_cache', ['md5_hash'], unique=False)
    op.create_index(op.f('idx_cv_cache_expires'), 'cv_parse_cache', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_application_events_id'), table_name='application_events')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    # ── Supprimer les types Enum ─────────────────────────────
    op.execute("DROP TYPE IF EXISTS application_status_v2")
    op.execute("DROP TYPE IF EXISTS manager_decision_v2")
    # ### end Alembic commands ###